### ISSUE TITLE
Cannot install created apk

### ISSUE THREAD

**Issue by johnwick123** [odensc/janus#1]
Is my step true?
1. first generate new dex 
2. replace dex with old one
3. zip the unzip apk
But I cannot install the new generated apk in any phone.
I'm sorry for my bad English.

**Comment by odensc** [comment]
No, your steps are incorrect.

1. Generate new dex file
2. Run command `python janus.py [-h] original-apk dex-file output-apk`
    original-apk = the original apk to use
    dex-file = the new dex file to replace the old one with
    output-apk = filename to write the new apk to

Then just install the generated apk.

**Comment by johnwick123** [comment]
Generate a new apk but in installing time, get Parse Error.

'''

Parse Error

There is a problem parsing the package.

'''

Sent from Outlook<http://aka.ms/weboutlook>
________________________________

**Comment by odensc** [comment]
What is the Security Patch Level of the Android phone?

**Comment by johnwick123** [comment]
The phone I tested is not patch. I'm sure.

**Comment by odensc** [comment]
Could you possibly send me the APK you are using? I will take a look.

**Comment by johnwick123** [comment]
Thanks. I'm going to send it to your email.

**Comment by odensc** [comment]
What version of Python are you using, and does the apkSigningVersion of the APK = 1?
